---
test-length: 30 
test-interval: 10
server-port: 15225 
grafana-address: localhost
grafana-port: 2003
tsdb-download-prefix: bandwidth.download
tsdb-upload-prefix: bandwidth.upload
iperf-servers:
  - 190.196.123.108: GTDLocal 
  - speedtest-br.grupogtd.com: GTDInternacional
  - 200.29.48.223: GTDNacional
conexiones-descarga: 10
conexiones-subida: 5 
