#!/bin/bash
#
clear
memoria_minima=7000
memoria_sistema=$(free -m |awk '/^Mem:/{print $2}')


if [ $memoria_sistema -ge $memoria_minima ]; then
    echo "Memoria fisica instalada cumple con el perfil recomendado"
else
### Verificacion de ram
echo  "####################### MEMORIA INSUFICIENTE ###########################"
echo  "La cantidad de memoria ram de este equipo no cumple con el minimo requerido"
echo  "Cantidad de ram detectada: $memoria_sistema MB"
echo  "Cantidad de ram necesaria: $memoria_minima MB"
echo  "Se han limitado las pruebas solo a las que son basadas en texto o cli."
echo  "########################################################################"
read -p "Presione [ENTER] para continuar..."
touch /home/gtd/.ramlock
clear
fi

if [ -f "/home/gtd/gographite_go-graphite.tar" ]; then
    echo "ISO actualizada"
else
echo  "#################### NUEVA VERSION DISPONIBLE #########################"
echo  "Existe una nueva version de este aplicativo, por favor"
echo  "Descargue la imagen desde http://nacional.grupogtd.com/Ubuntu-BWTester-GTD.iso"
echo  "y grabela en el pendrive segun lo indica el procedimiento."
echo  "Si esta certificando un enlace satelital(vsat) o menor a 50 Mbps"
echo  "prefiera el uso de las pruebas basadas en texto o cli"
echo  "########################################################################"
read -p "Presione [ENTER] para continuar..."
clear
fi

sudo systemctl stop systemd-resolved
sudo rm -f /etc/resolv.conf
#sudo bash -c 'echo "nameserver 200.75.0.4" > /etc/resolv.conf'
#sudo bash -c 'echo "nameserver 200.75.0.5" >> /etc/resolv.conf'
sudo bash -c 'echo "nameserver 8.8.8.8" > /etc/resolv.conf'
sudo bash -c 'echo "nameserver 1.1.1.1" >> /etc/resolv.conf'
sudo timedatectl set-timezone America/Santiago
#anydesk
wget -qO - https://keys.anydesk.com/repos/DEB-GPG-KEY | sudo apt-key add -
sudo bash -c 'echo "deb http://deb.anydesk.com/ all main" > /etc/apt/sources.list.d/anydesk-stable.list'
#
echo "Actualizando repositorios"
sudo apt -qqq update 
echo "Actualizacion finalizada"
pkgs='dialog ntpdate anydesk'
if ! dpkg -s $pkgs >/dev/null 2>&1; then
  sudo apt -qqqq install  $pkgs
  echo "Cliente NTP, Dialog y AnyDesk han sido instalados con exito"
else
  echo "Cliente NTP, Dialog y Anydesk se encuentran presentes en el sistema"
fi
echo "Actualizando hora de la maquina con ntp.shoa.cl"
sudo ntpdate -u -t 3 ntp.shoa.cl
cd /home/gtd
prereq=(
    bwtest.fo.ftth.bash
    bwtest.vsat.lb.bash
    bwtest.vsat.lb.txt.bash
    speedtest.net.sh
    bwtest.fo.ftth.txt.bash
    python-packages.tar.gz
    pinger
)
for i in "${prereq[@]}"; do
if [[ -f "/home/gtd/$i" ]]
    then
    echo "Archivo $i existente en el sistema"
else
    wget -q --no-check-certificate https://velocidad.grupogtd.com/bwtest/$i -O $i
    chmod +x $i
    fi
done


# Modulos python3 portables
if [ ! -f "/home/gtd/.pygzlock" ]
    then
    echo "Instalando modulos python3"
    tar -zxf python-packages.tar.gz -C /home/gtd/.local
    touch /home/gtd/.pygzlock
fi
#read -p "Presione [ENTER] para continuar..."

# El menu de opciones esta determinado segun la ram disponible
if [[ -f "/home/gtd/.ramlock" ]]
    then
    wget -q --no-check-certificate https://velocidad.grupogtd.com/bwtest/menu.ramlock.bash -O /home/gtd/menu.bash
    chmod +x /home/gtd/menu.bash
else
    wget -q --no-check-certificate https://velocidad.grupogtd.com/bwtest/menu.bash -O /home/gtd/menu.bash
    chmod +x /home/gtd/menu.bash
fi
#Configuracion de anydesk
mkdir -p /home/gtd/.anydesk

cat <<EOF > /home/gtd/.anydesk/user.conf
ad.ui.lang=es
ad.audio.playback_device=auto_null
ad.audio.transmit_source=auto_null.monitor
ad.roster.favorites=
ad.roster.items=
ad.msg.data=
ad.roster.adv_view=false
ad.audio.transmit=false
ad.audio.playback=false
ad.ui.lang.auto=false
EOF

#Cambiamos el teclado a español
dconf write /org/gnome/desktop/input-sources/sources "[('xkb', 'es')]"

#Cambiamos los iconos de app favoritas
dconf write /org/gnome/shell/favorite-apps "['firefox.desktop', 'anydesk.desktop', 'org.gnome.Terminal.desktop']"

#Actualizamos
dconf update

clear
###
echo  "############# Detectando IP Publica ##########################"
# IP publica
IP=$(curl --silent ifconfig.me)
echo ""
echo  "IP PUBLICA DETECTADA: $IP"
echo ""
echo  "##############################################################"
echo $IP > /home/gtd/.ippublica
read -p "Presione [ENTER] para continuar..."

rm -f upme
bash /home/gtd/menu.bash