#!/bin/bash
#
sudo systemctl stop systemd-resolved
sudo rm -f /etc/resolv.conf
#sudo bash -c 'echo "nameserver 200.75.0.4" > /etc/resolv.conf'
#sudo bash -c 'echo "nameserver 200.75.0.5" >> /etc/resolv.conf'
sudo bash -c 'echo "nameserver 8.8.8.8" > /etc/resolv.conf'
sudo bash -c 'echo "nameserver 1.1.1.1" >> /etc/resolv.conf'
sudo timedatectl set-timezone America/Santiago
echo "Actualizando repositorios"
sudo apt update -qqq
echo "Actualizacion finalizada"
cd /home/gtd
prereq=(
    menu.bash
    bwtest.fo.ftth.bash
    bwtest.vsat.lb.bash
    speedtest.net.sh
)
for i in "${prereq[@]}"; do
if [[ -f "/home/gtd/$i" ]]
    then
    echo "Archivo $i existente en el sistema"
else
    wget --no-check-certificate https://velocidad.grupogtd.com/bwtest/$i -O $i
    chmod +x $i
    fi
done

pkgs='dialog'
if ! dpkg -s $pkgs >/dev/null 2>&1; then
  sudo apt install -qqq $pkgs
fi

bash /home/gtd/menu.bash